### ISSUE TITLE
There is an error when using the library on a React project that created with Vite

### ISSUE THREAD

**Issue by IradDoron** [mondaycom/monday-ui-react-core#1185]
When created a React project with "pnpm create vite", and using the TypeScript template, there is an error when using a component:

index.js:19 Uncaught ReferenceError: global is not defined
    at ensureCache2 (index.js:19:2)
    at node_modules/global-cache/index.js (index.js:29:13)
    at __require2 (chunk-6FBSFQRG.js?v=f166bd8d:18:50)
    at node_modules/react-with-styles-interface-css/dist/index.js (index.js:12:43)
    at __require2 (chunk-6FBSFQRG.js?v=f166bd8d:18:50)
    at node_modules/react-with-styles-interface-css/index.js (index.js:2:18)
    at __require2 (chunk-6FBSFQRG.js?v=f166bd8d:18:50)
    at node_modules/monday-ui-react-core/node_modules/react-dates/lib/utils/registerCSSInterfaceWithDefaultTheme.js (registerCSSInterfaceWithDefaultTheme.js:10:59)
    at __require2 (chunk-6FBSFQRG.js?v=f166bd8d:18:50)
    at node_modules/monday-ui-react-core/node_modules/react-dates/lib/initialize.js (initialize.js:5:68)

**Comment by itaim18** [comment]
Did you try installing it through pnpm as well? Because it looks like it is only available on npm...

**Comment by orrgottlieb** [comment]
@IradDoron can you share a demo repo?
I will try to use Vite, but a demo repo will be a huge help

**Comment by IradDoron** [comment]
> Did you try installing it through pnpm as well? Because it looks like it is only available on npm...

On a project with a Vite setup, it is not working with installation using pnpm or npm

**Comment by IradDoron** [comment]
> @IradDoron can you share a demo repo? I will try to use Vite, but a demo repo will be a huge help

Here is a demo repo to demonstrate the problem: https://github.com/IradDoron/demo-vite-setup-monday-ui-not-working

I created a React project using the npm create vite command, and chose the TypeScript template. In the App component, I added a Button component from the monday-ui-react-core library. However, when I tried to view the project in the browser, I encountered the following error:

Uncaught ReferenceError: global is not defined
    at ensureCache2 (index.js:19:2)
    at node_modules/global-cache/index.js (index.js:29:13)
    at __require2 (chunk-6FBSFQRG.js?v=774c9b58:18:50)
    at node_modules/react-with-styles-interface-css/dist/index.js (index.js:12:43)
    at __require2 (chunk-6FBSFQRG.js?v=774c9b58:18:50)
    at node_modules/react-with-styles-interface-css/index.js (index.js:2:18)
    at __require2 (chunk-6FBSFQRG.js?v=774c9b58:18:50)
    at node_modules/monday-ui-react-core/node_modules/react-dates/lib/utils/registerCSSInterfaceWithDefaultTheme.js (registerCSSInterfaceWithDefaultTheme.js:10:59)
    at __require2 (chunk-6FBSFQRG.js?v=774c9b58:18:50)
    at node_modules/monday-ui-react-core/node_modules/react-dates/lib/initialize.js (initialize.js:5:68)

**Comment by ThinhLe183** [comment]
go to ### vite.config.ts

```
export default defineConfig({
  plugins: [react()],
  define: {
    global: {},
  },
})
```

**Comment by IradDoron** [comment]
@ThinhLe183 It's working! thanks everyone 
Can I add this information to the README file?

**Comment by ThinhLe183** [comment]
@IradDoron Yeah, sure

**Comment by orrgottlieb** [comment]
@IradDoron @ThinhLe183 this is related to Vite config and not to the monday-ui-react-core, thus shouldn't be in our README file
